name: Deploy to gh-pages

on:
  push:
    branches: master
  pull_request:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Use SSH key 🔑
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}} > ~/.ssh/id_rsa"
          sudo chmod 600 ~/.ssh/id_rsa
      
      - name: Git User config ⚙️
        run: |
          git config --global user.email "alicia.guardenoalbertos@gmail.com"
          git config --global user.name "Alicia G."

      - name: Install 🔧
        run: npm install

      - name: Lint 🧐
        run: npm run lint:fix

      - name: Prettier 💅
        run: npm run format

      - name: Test 🚨
        run: npm test

      - name: Build 🏗️
        run: npm run build:prod

      - name: Deploy 🚀
        run: npm run deploy:gh-pages -- -r git@github.com:Firenz/chuck-norris-facts.git
